Bzr 48 notification crud
ardiesan/bazaar pull request #29
Opened 2022-10-07 07:25 UTC by dr0psh0t

## Overview
- Creating Notification CRUD

## Change Summary
- Added notification page
- Added notification form page

## Jira Ticket
- https://ardie.atlassian.net/browse/BZR-48

2022-10-10 05:16 UTC, ardiesan requested changes
- Kindly check if there is a way to put two route for a single display or functionality
- The mapping is redirecting to english, there should be no hardcoded redirect path.

2022-10-11 01:03 UTC, ardiesan commented on src/main/java/com/jadc/bazaar/controller/DefaultLanguageController.java
> +		return "redirect:/ja/admin/notification/index";
There should be no hard-coded locale.

2022-10-11 01:46 UTC, dr0psh0t commented on src/main/java/com/jadc/bazaar/controller/DefaultLanguageController.java
> +		return "redirect:/ja/admin/notification/index";
@ardiesan 

Done addressing for these requested changes:
- put two route for a single display
- mapping redirecting to english
- no hardcoded locale in redirect

Would like to request code review again

2022-10-11 02:11 UTC, ardiesan approved these changes

2022-10-11 02:11 UTC, merged